project:
  type: book

book:
  title: "Lamalab Tool and Paper Notes"
  author: "LamaLab"
  date: "4/11/2024"
  chapters:
    - index.qmd
    - part: Tools
      chapters:
        - tools/hydra.qmd
        - tools/ip_rotator.qmd
        - tools/polars.qmd
        - tools/thunder_client.qmd
        - tools/tmux.qmd
        - tools/trimean.ipynb
        - tools/pandarallel.ipynb
        - tools/bfg.qmd
        - tools/showyourwork.qmd
    - part: Papers
      chapters:
        - papers/llm4mat.qmd
        - papers/chem_yield_prediction_2024.md
        - papers/dagdelen_data_extraction.md
        - papers/MolCLR_2024.md
        - papers/PaCh.md
        - papers/ms_prediction_graph_transformers/tandem_ms_prediction_graph_transformers.qmd
        - papers/open-source-cheminformatics.qmd
        - papers/universal_chiral_fp_2024.md
        - papers/lwreg_2024.md
        - papers/tango.md

bibliography: references.bib
# csl: nature.csl

format:
  html:
    theme: cosmo
    number-sections: false

